name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        pip install -r requirements.txt

    - name: Lint Code
      run: |
        pip install flake8
        flake8 . --count --exit-zero --max-complexity=10

    - name: Build Docker Image
      run: |
        docker build -t ghcr.io/${{ github.repository }}:latest .

    - name: Push to GitHub Container Registry
      run: |
        echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
        docker push ghcr.io/${{ github.repository }}:latest

    - name: Deploy to Kubernetes
      env:
        KUBECONFIG: ${{ secrets.KUBECONFIG }}
      run: |
        kubectl config set-context --current --namespace=default
        kubectl set image deployment/your-deployment-name your-container-name=ghcr.io/${{ github.repository }}:latest

